Feature/umec 462
UMEC-Corp/Utilities.Billing pull request #3
Opened 2024-08-29 07:15 UTC by klogo-hopper

2024-09-05 11:00 UTC, dmitrynadolin commented on src/Utilities.Billing.StellarWallets/Extensions.cs
> +    public static IServiceCollection UseStellarWallets(this IServiceCollection services, ConfigurationManager configuration)
Желательно передавать конкретную секцию, а не всю конфигурацию, либо ConfigurationManager + название секции. Сейчас сложно искать информацию, как секция должна называться

2024-09-05 11:01 UTC, dmitrynadolin commented on src/Utilities.Billing.Contracts/ITenantGrain.cs
Надо классы вынести в отдельные файлы

2024-09-05 11:02 UTC, dmitrynadolin commented on src/Utilities.Billing.Api/GrpcServices/Extensions.cs
> +        var claimValue = "1B9946C6-1916-4FB9-963A-8283EE73F0F3"; // user.FindFirstValue("client_tenant") ?? throw new InvalidOperationException("'client_tenant' claim is missing.");
Плохо, что в код попадают магические строки. Надо это переделать как-то.

2024-09-05 11:08 UTC, dmitrynadolin commented on src/Utilities.Billing.StellarWallets/StellarWalletsClient.cs
> +        return KeyPair.FromSecretSeed(_options.CurrentValue.SecretSeed).AccountId;
Если SecretSeed обязательно должен книфгурироваться явно, хорошо бы для опций добавить реалиацию IValidateOptions

2024-09-05 11:09 UTC, dmitrynadolin requested changes
Оставил комментарии

2024-09-06 09:09 UTC, klogo-hopper commented on src/Utilities.Billing.Api/GrpcServices/Extensions.cs
> +        var claimValue = "1B9946C6-1916-4FB9-963A-8283EE73F0F3"; // user.FindFirstValue("client_tenant") ?? throw new InvalidOperationException("'client_tenant' claim is missing.");
На момент разработки не было понимая, откуда будет браться tenant_id, поэтому вписал явно в код. Сейчас это уже неактуально и в UMEC-471 было изменено

2024-09-06 09:46 UTC, klogo-hopper commented on src/Utilities.Billing.StellarWallets/Extensions.cs
> +    public static IServiceCollection UseStellarWallets(this IServiceCollection services, ConfigurationManager configuration)
добавил

2024-09-06 09:46 UTC, klogo-hopper commented on src/Utilities.Billing.StellarWallets/StellarWalletsClient.cs
> +        return KeyPair.FromSecretSeed(_options.CurrentValue.SecretSeed).AccountId;
сделал

2024-09-06 10:11 UTC, klogo-hopper commented on src/Utilities.Billing.Contracts/ITenantGrain.cs
будет разделено в 483

2024-09-06 10:15 UTC, merged