Feature/umec 471
UMEC-Corp/Utilities.Billing pull request #4
Opened 2024-08-29 07:18 UTC by klogo-hopper

2024-09-05 11:15 UTC, dmitrynadolin requested changes

2024-09-05 11:15 UTC, dmitrynadolin commented on src/Utilities.Billing.Api/GrpcServices/Extensions.cs
> +    public static ITenantGrain GetTenant(this IGrainFactory clusterClient, string stringTenantId)
Это плохой метод. Название намекает, что там внутри что-то существенное, а по сути он только заменяет Guid.Parse.

2024-09-05 11:15 UTC, dmitrynadolin commented on src/Utilities.Billing.Contracts/IPaymentSystem.cs
> +public class AddStellarAssetCommand
Надо пернести в отдельный файл

2024-09-05 11:15 UTC, dmitrynadolin commented on src/Utilities.Billing.Contracts/ITenantGrain.cs
> +[GenerateSerializer]
Каждый класс должен уехать в совй файл.

2024-09-06 10:11 UTC, klogo-hopper commented on src/Utilities.Billing.Contracts/ITenantGrain.cs
> +[GenerateSerializer]
будет разделено в 483

2024-09-06 10:11 UTC, klogo-hopper commented on src/Utilities.Billing.Contracts/IPaymentSystem.cs
> +public class AddStellarAssetCommand
будет разделено в 483

2024-09-06 10:43 UTC, merged